### ISSUE TITLE
Not all recommended packages available in Ubuntu 18.04 LTS repos

### ISSUE THREAD

**Issue by roldugin** [PacktPublishing/Linux-Kernel-Programming#10]
Running the following command from `Chapter 2: Kernel Workspace Setup` I get some errors I thought I would report:

```
$ sudo apt install git fakeroot build-essential tar ncurses-dev tar xz-utils libssl-dev bc stress python3-distutils libelf-dev linux-headers-$(uname -r) bison flex libncurses5-dev util-linux net-tools linux-tools-$(uname -r) exuberant-ctags cscope sysfsutils gnome-system-monitor curl perf-tools-unstable gnuplot rt-tests indent tree pstree smem libnuma-dev numactl hwloc bpfcc-tools sparse flawfinder cppcheck tuna hexdump openjdk-14-jre trace-cmd virt-what
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libncurses5-dev' instead of 'ncurses-dev'

E: Unable to locate package pstree
E: Unable to locate package tuna
E: Unable to locate package hexdump
E: Unable to locate package openjdk-14-jre
```

Using Ubuntu 64 bit 18.04.6 release as recommended.

**Comment by kaiwan** [comment]
Thanks v much for pointing this out Roldugin!
My mistake. Here's what I could find out:

pstree:
 is in the package named psmisc
tuna: 
 it's a Python script; pl [refer this site for installation](https://tuna.readthedocs.io/en/stable/installation.html) 
hexdump:
is in the package named bsdmainutils
openjdk-14-jre:
Pl [refer this site](https://java.tutorials24x7.com/blog/how-to-install-openjdk-14-on-ubuntu)

HTH.
