### ISSUE TITLE
Is it safe to iterate task list without any lock?

### ISSUE THREAD

**Issue by iwoeruhsdfwoi** [PacktPublishing/Linux-Kernel-Programming#11]
I'm not sure whether it's safe to traverse this list without any lock. I examined all usages and most of them are protected by `rcu_read_lock()` or `read_lock(&tasklist_lock)`.
https://github.com/PacktPublishing/Linux-Kernel-Programming/blob/7c72a6e8cba86b6c527ce6467872488dcea26253/ch6/foreach/prcs_showall/prcs_showall.c#L51

**Comment by kaiwan** [comment]
Hi @iwoeruhsdfwoi , thanks for your comment.
You're right reg the need for protection. 
Do understand though, that this is a book where the reader makes progress as (s)he covers each chapter.
The locking / synchronization details are left to the last two chapters...
In fact, this statement in the book in Ch 6 (pg 311 of the e-book) hints at this:

> ...
> We print the name of the thread as well (by looking up the comm member of
> the task structure). You might question why we don't use the get_task_comm() routine to obtain the task's name here; the short
> reason: it causes a deadlock! We shall explore this (and how to avoid it) in detail in the later chapters on kernel synchronization. For now, again, we just do it the simple way.
> ...

This is again mentioned in Ch 12 pg 668.
As you've written reg this, I'll put relevant info in a comment in these examples. Thanks.
