### ISSUE TITLE
Having trouble booting the 5.4 kernel on Ubuntu Jammy 22.04

### ISSUE THREAD

**Issue by redbilledpanda** [PacktPublishing/Linux-Kernel-Programming#13]
Hello Kaiwan.

I've been using your book to revamp my rusty Linux kernel programming knowledge. I was out of the loop since the 3.x days.
I'm on Ubuntu 22 (Jammy) running kernel version 5.15. I git cloned tag v5.4 of the upstream stock kernel and did as your book mentioned. First off, I ran into the following problem and fixed it as mentioned [here](https://www.spinics.net/lists/kernel/msg3797871.html)
  ```
  arch/x86/entry/thunk_64.o: warning: objtool: missing symbol table
  make[2]: *** [scripts/Makefile.build:357: arch/x86/entry/thunk_64.o] Error 1
  make[2]: *** Deleting file 'arch/x86/entry/thunk_64.o'
  make[1]: *** [scripts/Makefile.build:509: arch/x86/entry] Error 2
  make[1]: *** Waiting for unfinished jobs....
  ```

Then, I again ran into the following problem and fixed it as mentioned [here](https://lkml.iu.edu/hypermail/linux/kernel/2001.3/05638.html)
```
LD  arch/x86/boot/compressed/vmlinux
ld: arch/x86/boot/compressed/pgtable_64.o:(.bss+0x0): multiple definition of `__force_order';
arch/x86/boot/compressed/kaslr_64.o:(.bss+0x0): first defined here
```
I was finally able to build and install the modules and the kernel. But then I ran into this:

![image](https://user-images.githubusercontent.com/46345560/225518150-63a4b904-1afa-4848-91cf-74bafe929204.png)
On googling, I resorted to manually editing the ``/etc/initramfs-tools/initramfs.conf`` file to replace the _ZSTD_ compression algorithm with gzip. Now the initramfs gets decompressed but it drops to the initramfs prompt since it cannot boot into the rootfs. From the picture below, initramfs says it was not able to find where the rootfs is located:</br>
 ![image](https://user-images.githubusercontent.com/46345560/225526935-e8c638ec-00b2-49b5-968e-91d7dcdae2d7.png)

It looks like I'm running into circles just getting this thing up and running. Do you have any suggestions?

**Comment by kaiwan** [comment]
Hi @redbilledpanda ,

Thanks for writing..
It's peculiar that you're running into issues with a stable 5.4 kernel. 
Could you try simplifying: download a stable kernel source tree from kernel.org (f.e. the latest 5.10 LTS as of now
is 5.10.169; here:
https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/linux-5.10.169.tar.xz
).

Build it via the usual steps as shown in the book. 
Am working on the 2nd edition; here's a simple wrapper script to build the kernel:
https://github.com/PacktPublishing/Linux-Kernel-Programming_2E/blob/main/ch2/kbuild.sh 

HTH! Lemme know..

**Comment by redbilledpanda** [comment]
Hello @kaiwan 

I believe the kernel build process is so tightly coupled with the underlying build infrastructure that certain things are taken for granted. Problems like the ones arise when we try do go against the established norm, like using a _recent_ build system to compile a _relatively_ older kernel. I am actually a bit aghast at the huge amount of complexity that has gone into the build process itself. For instance, building the 5.10.169 version of the kernel on my machine gives this error:
```
make[1]: *** No rule to make target 'debian/canonical-revoked-certs.pem', needed by 'certs/x509_revocation_list'.  Stop.
make[1]: *** Waiting for unfinished jobs....
```

As [this](https://stackoverflow.com/questions/67670169/compiling-kernel-gives-error-no-rule-to-make-target-debian-certs-debian-uefi-ce) post mentions, I could actually disable the whole key related shebang or else I would have to actually install a certificate that the kernel build process recognizes. 

Anyways, I'll keep you updated and thanks for writing such a detailed book. After ULK and LKD which are great but way too old now, this will be my go to book. Additionally, it's good to know that a second edition is also on the cards!

**Comment by kaiwan** [comment]
> Hello @kaiwan
> 
> IMHO, the kernel build process is so tightly coupled with the underlying build infrastructure that certain things are taken for granted. Problems like the ones I mentioned above arise when we try do go against the established norm, like using a _recent_ build system to compile a _relatively_ older kernel. I am actually a bit aghast at the huge amount of complexity that has gone into the build process itself vis-a-vis getting the configuration just right enough to build and boot. 

Hm, yeah... we have to take the good with the bad..

>For instance, building the 5.10.169 version of the kernel on my machine gives this error:
> 
> ```
> make[1]: *** No rule to make target 'debian/canonical-revoked-certs.pem', needed by 'certs/x509_revocation_list'.  Stop.
> make[1]: *** Waiting for unfinished jobs....
> ```
> 
> As [this](https://stackoverflow.com/questions/67670169/compiling-kernel-gives-error-no-rule-to-make-target-debian-certs-debian-uefi-ce) post mentions, I could actually disable the whole key related shebang or else I would have to actually install a certificate that the kernel build process recognizes.

Yes.. my helper script simply disables it...
> 
> So I went with the second option of installing certfificates, taking help from the above link. After that, I was able to finally boot into this kernel, sigh! 
Nice!

>By the way, how is it that even with this new kernel, the existing window manager (LXDE in my case) starts without any issue as if nothing happened? Can we say that the window manager startup daemon (it has to be a daemon after all right?) is abstracted from the rootfs layout process? If not how to explain it?

It's just this- the kernel has very loose coupling with the rootfs; thus, it simply works.. things break when you use a very old rootfs with newer kernels (>=3.x) or vice-versa..
> 
> Anyways, thanks for being so responsive and prompt and for writing such a detailed book. After ULK and LKD which are great but way too old now, this will be my go to book. 

Thanks you!
>Additionally, it's good to know that a second edition is also on the cards! I hope it'll be coming out soon and be available on Safari (the learning platform).
Well, it'll be available on the Packt platform at least...
Thanks for writing in, and the very best with kernel adventures :-)
