### ISSUE TITLE
ch6: viewing userspace stack for bash using gdb

### ISSUE THREAD

**Issue by redbilledpanda** [PacktPublishing/Linux-Kernel-Programming#16]
Hello @kaiwan 

I was reading ch6, section entitled `Viewing the user space stack of a given thread or process` in which you mentioned that the `pstack` utility on Ubuntu doesn't work as expected and it's better to use gdb to view the userspace backtrace. So I attempted this exercise but I am unable to make it work.

I'll describe my steps here:

1.  Attach gdb to the running kernel (loaded into memory) using the `/proc/kcore` file like so:
```
cd $LinuxSrcDir
sudo gdb vmlinux /proc/kcore
```
2. attach to the thread running bash (in my case TID 1283) like so:
```
(gdb) attach 1283
```
After a warning stating there being a 'build ID' mismatch `vmlinux` and `/usr/bin/bash`, it gives me this:

![image](https://user-images.githubusercontent.com/46345560/230549155-2598840b-dfec-4300-8899-c5a0a79aae3f.png)

Issuing a bt gives me this:
![image](https://user-images.githubusercontent.com/46345560/230548518-46b719e0-e1e4-40e5-8a1c-3ffe50d1b5df.png)

I can understand the missing function names for the userspace portion of the process. However, the kernel space of that process should have shown something. Right? Reading the `procfs` entry for TID 1283 however makes a lot more sense. 
![image](https://user-images.githubusercontent.com/46345560/230548734-f60b2fe4-8ee7-4ffe-9c13-c1b13aa48bea.png)

Am I doing this incorrectly, or is this something to be expected? By the way, FYI this kernel has been compiled with the `-ggdb` flag passed to the top level makefile via `KCFLAGS` so I know the symbols are intact.

**Comment by kaiwan** [comment]
> Hello @kaiwan
> 
> I was reading ch6, section entitled `Viewing the user space stack of a given thread or process` in which you mentioned that the `pstack` utility on Ubuntu doesn't work as expected and it's better to use gdb to view the userspace backtrace. So I attempted this exercise but I am unable to make it work.
> 
> I'll describe my steps here:
> 
> 1. Attach gdb to the running kernel (loaded into memory) using the `/proc/kcore` file like so:
> 
> ```
> cd $LinuxSrcDir
> sudo gdb vmlinux /proc/kcore
> ```

So, don't do that, don't try and have GDB work with the kernel image... we want to view the _user_ space stack only...
So, instead, compile the C usermode app with the -g switch and then run it (in a terminal)..
In another terminal, run GDB as root and perform the 'attach <PID>' cmd; now do 'bt', it should just work.

Thanks for asking and let me know!
Hope you're enjoying the book (the fact you're working hands-on with it is a really good sign!).
> 
> 2. attach to the thread running bash (in my case TID 1283) like so:
> 
> ```
> (gdb) attach 1283
> ```
> 
> After a warning stating there being a 'build ID' mismatch `vmlinux` and `/usr/bin/bash`, it gives me this:
> 
> ![image](https://user-images.githubusercontent.com/46345560/230549155-2598840b-dfec-4300-8899-c5a0a79aae3f.png)
> 
> Issuing a bt gives me this: ![image](https://user-images.githubusercontent.com/46345560/230548518-46b719e0-e1e4-40e5-8a1c-3ffe50d1b5df.png)
> 
> I can understand the missing function names for the userspace portion of the process. However, the kernel space of that process should have shown something. Right? Reading the `procfs` entry for TID 1283 however makes a lot more sense. ![image](https://user-images.githubusercontent.com/46345560/230548734-f60b2fe4-8ee7-4ffe-9c13-c1b13aa48bea.png)
> 
> Am I doing this incorrectly, or is this something to be expected? By the way, FYI this kernel has been compiled with the `-ggdb` flag passed to the top level makefile via `KCFLAGS` so I know the symbols are intact.
