### ISSUE TITLE
Some typos in this book.

### ISSUE THREAD

**Issue by xuhw21** [PacktPublishing/Linux-Kernel-Programming#17]
Hi @kaiwan, Thanks for writing this excellent book.
After reading this book thoroughly, i found some typos which you may could help to correct it.

1. In Page 155,  Double 'w' used at line "// ch4/helloworld_lkm/hello**ww**orld_lkm.c". red line marked as below.
![image](https://user-images.githubusercontent.com/78025123/231951939-3c4a0c64-698d-45a1-9b24-4e19f2634fa0.png)

2. In Page 307, at line " first and second columns in the preceding code block that represent the **TGID and PID** respectively". From the configure below, In fact,  " first and second columns in the preceding code block that represent the **PID and TGID** respectively"
![image](https://user-images.githubusercontent.com/78025123/231952471-26ea1050-4c5c-4f0b-b4bf-f2e9ebcb30aa.png)

3. In Page 656, at last line, "In place of atomic64_dec_if_positive(), use
atomic64_dec_if_positive()." It may should be  "In place of atomic_dec_if_positive(), use
atomic64_dec_if_positive()."
![image](https://user-images.githubusercontent.com/78025123/231953162-1f717540-eb07-47ce-885e-a6d60a1f6c15.png)

Thanks
Hengwei

**Comment by kaiwan** [comment]
> Hi @kaiwan, Thanks for writing this excellent book. 
Thank you!
>After reading this book thoroughly, i found some typos which you may could help to correct it.
> 
> 1. In Page 155,  Double 'w' used at line "// ch4/helloworld_lkm/hello**ww**orld_lkm.c". red line marked as below.
>    ![image](https://user-images.githubusercontent.com/78025123/231951939-3c4a0c64-698d-45a1-9b24-4e19f2634fa0.png)

Thanks; now marked in the README.md under the '**Known Errata**' section

> 2. In Page 307, at line " first and second columns in the preceding code block that represent the **TGID and PID** respectively". From the configure below, In fact,  " first and second columns in the preceding code block that represent the **PID and TGID** respectively"
>    ![image](https://user-images.githubusercontent.com/78025123/231952471-26ea1050-4c5c-4f0b-b4bf-f2e9ebcb30aa.png)

This typo has already been caught :-)
See in the 'Known Errata'

> 3. In Page 656, at last line, "In place of atomic64_dec_if_positive(), use
>    atomic64_dec_if_positive()." It may should be  "In place of atomic_dec_if_positive(), use
>    atomic64_dec_if_positive()."
>    ![image](https://user-images.githubusercontent.com/78025123/231953162-1f717540-eb07-47ce-885e-a6d60a1f6c15.png)
> 
Thanks; now marked in the README.md under the '**Known Errata**' section

> Thanks Hengwei
Thank you very much
