### ISSUE TITLE
p26: "sudo apt install git fakeroot...": utillinux -> util-linux

### ISSUE THREAD

**Issue by seantywork** [PacktPublishing/Linux-Kernel-Programming#19]
great book!
however it looks like the package utillinux has been renamed to util-linux.
just mentioning it for other folks

**Comment by kaiwan** [comment]
You're right, thank you!
It now should be util-linux .
(BTW, am working on the LKP 2nd Ed; it has an install script!
https://github.com/PacktPublishing/Linux-Kernel-Programming_2E/blob/main/ch1/pkg_install4ubuntu_lkp.sh 

(and it installs the util-linux package!)
