### ISSUE TITLE
is it compatible to use your first edition in ubunut 22.04

### ISSUE THREAD

**Issue by hariharan382** [PacktPublishing/Linux-Kernel-Programming#20]
hi sir, I am getting started with kernel, is it ok to use 22.04, or else should I have to use 18.04, and when is your latest book on kernel development is releasing sir(sorry to raise this as issue sir)

**Comment by kaiwan** [comment]
Np. You can use Ubuntu 22.04.. There might be small differences in package versions, but overall it should work for kernel dev.
Am working on the 2nd ed of the LKP book, should hopefully be done by September.

**Comment by kaiwan** [comment]
OK, closing
