### ISSUE TITLE
Possible free_pages() issue in sample code (book text example code is correct)

### ISSUE THREAD

**Issue by brian-wood** [PacktPublishing/Linux-Kernel-Programming#22]
Hi Kaiwan, 

I was just working on the example code for chapter 8's lowlevel_mem.c and noticed that in line 126 issuing the call for pointer requesting 5 pages:
          gptr5 = page_address(alloc_pages(GFP_KERNEL, 5));
But in the exit function it appears to only be freeing 3 pages: 
          free_pages((unsigned long)gptr5, 3);

I've confirmed the code snippet shown in the current book is correct (uses 3 in both the alloc/free). Maybe the name gptr'5' caused the use of '5' instead of '3' during the allocation in the sample file. :-)

I have to say you have one of the best books I've read on kernel development (I also loved your kernel debugging book); I can't wait to read the updated version of this book with it's release in January 2024. 

All the best, 

Brian

**Comment by kaiwan** [comment]
Brian, thank you! For both- pointing out this bug (yes, leading to leakage at that!), and for appreciating the book..
Yeah, I guess the gptr5 confused me at some point :-)  (ah the perils of variable naming!). Have just updated the fix (and mentioned you in it !).

**Comment by brian-wood** [comment]
Hi Kaiwan, 

Thank you for the mention. I noticed another possible small update for the ch9 'vmalloc_demo.c' module. When I was typing out the code I noticed that it looks like the goto labels aren't using kvfree() for the kv/kvarr pointers, but in the module exit function kvfree is being used (I wasn't sure if this should be updated for consistency). :-) 

In vmalloc_try():

`#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 8, 0)
 err_out5:
	**vfree(kvarr);**
#endif
 err_out4:
	**vfree(kv);**
 err_out3:
	vfree(vptr_init);
 err_out2:
	vfree(vptr_rndm);
 err_out1:
	return -ENOMEM;`

In vmalloc_demo_exit(): 

`#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 8, 0)
	vfree(vrx);
#endif
	**kvfree(kvarr);**
	**kvfree(kv);**
	vfree(vptr_init);
	vfree(vptr_rndm);
	pr_info("removed\n");`

**Comment by brian-wood** [comment]
**test bold**
