### ISSUE TITLE
Possible memory leak in ch12 mutex/spinlock examples

### ISSUE THREAD

**Issue by brian-wood** [PacktPublishing/Linux-Kernel-Programming#23]
Hi Kaiwan, 

When working through the example code in chapter 12 for both the mutex and spinlock C files I noticed in the miscdrv_init_* functions the following comment & code which appears (I may be incorrect) to create a memory leak by not being free'd on module exit: 

        /*
	 * A 'managed' kzalloc(): use the 'devres' API devm_kzalloc() for mem
	 * alloc; why? as the underlying kernel devres framework will take care of
	 * freeing the memory automatically upon driver 'detach' or when the driver
	 * is unloaded from memory
	 */
	ctx = kzalloc(sizeof(struct drv_ctx), GFP_KERNEL);

Then in the exit function I didn't see a kfree() call: 

        static void __exit miscdrv_exit_mutexlock(void)
        {
	        mutex_destroy(&lock1);
	        mutex_destroy(&ctx->lock);
	        misc_deregister(&llkd_miscdev);
	        pr_info("LLKD misc driver %s deregistered, bye\n", llkd_miscdev.name);
        }

Should the initial allocation look like this so we don't need to free up the memory (letting the kernel handle deallocation): 
        ctx = devm_kzalloc(llkd_miscdev.this_device, sizeof(struct drv_ctx), GFP_KERNEL);

Or maybe the kfree()/kzfree() in the exit function just got missed being included? :-)

This has been one of the best kernel books I've read to date, looking forward to finishing the last chapter and moving onto book 2. 

Brian W.

**Comment by kaiwan** [comment]
Thanks again Brian!! Super catch... have fixed it (using the devm_kzalloc()), pl see in the repo.
May I request you to leave a review on Amazon reg the book.. thanks.
