### ISSUE TITLE
Missing sample code of Part 2

### ISSUE THREAD

**Issue by Aquarisx2** [PacktPublishing/Linux-Kernel-Programming#5]
I clone this repo but look like it doesn't contain the sample code for Part 2 but only the e-book. Please help check and update it.
Thanks.

**Comment by kaiwan** [comment]
The GitHub repo for the Linux Kernel Programming - Part 2 book is here:
https://github.com/PacktPublishing/Linux-Kernel-Programming-Part-2

Regards,
Kaiwan.
