### ISSUE TITLE
Ch 10 Question 8

### ISSUE THREAD

**Issue by vincentkfu** [PacktPublishing/Linux-Kernel-Programming#9]
Hello Kaiwan, I was confused by Ch 10 Question 8. Based on my reading of the book (p. 514) there are any number of runqueues. And as far as I could find, there was no discussion of waitqueues in the chapter.

The question and listed answer are:
```
8. On a modern Linux system with 4 CPU cores, there will be ___ runqueue(s) for
SMP scalability; how many waitqueues can it have: __
 1. 1, 4
 2. 4, any number
 3. 4, 1
 4. any number of, any number

A. option 2
```

**Comment by kaiwan** [comment]
Hi Vincent, thanks for writing. You're right. Q8 isn't quite right... I shall correct it, thank you!

Reg runqueues, page 510 says: 
_"Now, this is a key point: the kernel maintains one runqueue for every processor core and for every scheduling class! So, if we have a system with, say, eight CPU cores, then we will have 8 cores * 5 sched classes = 40 runqueues!"._

Also there is no  mention of waitqueues; a waitqueue is essentially  a per-event structure upon which tasks that are waiting on that event are enqueued. There can be any number of drivers having any number of events that are waited upon (blocking in nature); hence the number of waitqueues can be anything...

**Comment by kaiwan** [comment]
Just pushed the fix for this question; thanks Vincent

**Comment by kaiwan** [comment]
Updated Ch 10 Qs 8 as well
